project:
  type: default
  output-dir: _output
  execute-dir: project
  pre-render: ../scripts/setup-qmd.R
title: "Multiproxy analysis exploring patterns of diet and disease in dental calculus and skeletal remains from a 19th century Dutch population"
author:
  - name: Bjørn Peare Bartholdy
    corresponding: true
    email: b.p.bartholdy@arch.leidenuniv.nl
    #orcid: 0000-0003-1689-0557
    affiliations:
      - ref: leiden
  - name: Jørgen B. Hasselstrøm
    affiliations:
      - ref: aarhus
  - name: Lambert K. Sørensen
    affiliations:
      - ref: aarhus
  - name: Maia Casna
    affiliations:
      - ref: leiden
  - name: Menno Hoogland
    affiliations:
      - ref: leiden
  - name: Historisch Genootschap Beemster
    affiliations:
      - ref: hgb
  - name: Amanda G. Henry
    affiliations:
      - ref: leiden
affiliations:
  - id: leiden
    name: Department of Archaeological Sciences, Leiden University
    #address: Einsteinweg 2, 2333 CC, Leiden, Netherlands
  - id: aarhus
    name: Department of Forensic Medicine, Aarhus University
    #address: Palle Juul-Jensens Boulevard 99, 8200, Aarhus N, Denmark
  - id: hgb
    name: Historisch Genootschap Beemster
    #address: Postbus 73, 1462 ZH, Middenbeemster, Netherlands
title-block-published: "Last updated"
format:
  pci-pdf:
    output-file: "pcj-submission_v1.pdf"
    shift-heading-level-by: -1
    knitr: 
      opts_chunk: 
        fig-path: "../figures/pcj-"
  html:
    theme: cosmo
    output-file: "preprint-for-PCI_v3.html"
    keep-md: true
  pdf:
    keep-tex: true
    output-file: "preprint-for-PCI_v3.pdf"
    documentclass: article
    number-sections: true
    geometry:
      - top=10mm
      - bottom=10mm
      - left=30mm
      - heightrounded
    include-in-header:
      file: ../templates/_preface.tex
    template-partials:
      - ../templates/_authors.tex
      - ../templates/_affiliations.tex
      - ../templates/before-body.tex
  docx:
    output-file: "draft-manuscript-3.docx"
execute:
  freeze: auto
  echo: false
  warning: false
knitr:
  opts_chunk:
    message: false
    comment: "#>"
    fig-path: "../figures/"
    fig-dpi: 600
bibliography: references.bib
#csl: "apa.csl" # Insert path for the bib-style
abstract: |
  Dental calculus is an excellent source of information on the dietary patterns
  of past populations, including consumption of plant-based items. The detection
  of plant-derived residues such as alkaloids and their metabolites in dental
  calculus provides direct evidence of consumption by individuals within a
  population.
  We conducted a study on 41 individuals from Middenbeemster, a 19th century rural
  Dutch archaeological site. Skeletal and dental analysis was performed to explore
  potential relationships between pathological lesions and presence of alkaloids.
  Dental calculus
  was analysed using ultra-high-performance liquid chromatography-tandem
  mass spectrometry (UHPLC-ESI-MS/MS).
  We were able to detect nicotine, cotinine, caffeine, theophylline, and salicylic
  acid, suggesting the consumption of tea and
  coffee and smoking of tobacco on an individual scale, which is also confirmed
  by historic documentation and identification of pipe notches in the dentition.
  Nicotine and/or cotinine was present in 56% of individuals with at least one
  visible pipe notch.
  There is some influence of skeletal preservation on the detection
  of alkaloids, with higher quantities of compounds extracted
  from well-preserved individuals, and we observe a positive relationship between
  weight of the calculus sample and quantity of detected compounds, as well as
  between chronic maxillary sinusitis and the presence of multiple alkaloids.
  There are many limitations that will need to be addressed going
  forward with this type of analysis; we stress the need for more systematic
  research on the consumption of alkaloid-containing items and their subsequent
  concentration and preservation in dental calculus, in addition to how mode of
  consumption may affect concentrations in the dentition.
  Despite the limitations, this preliminary study illustrates many benefits
  of using calculus to target a variety of compounds that could have been consumed
  as medicine or diet. This method allows us
  to directly address specific individuals, which can be especially useful in
  individuals that are not always well-documented in historic documentation,
  such as rural populations, and especially children and women.
keywords: |
  dental calculus; LC-MS/MS; alkaloids; dental pathology; sinusitis; caffeine; tobacco
#highlights: |
 # These are the highlights.
